# Generated by Django 6.1.1 on 2026-09-24 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_sellerapplication_sellerprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerapplication',
            name='plan',
            field=models.CharField(choices=[('standard', 'Vendeur Standard'), ('premium', 'Vendeur Premium')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='plan',
            field=models.CharField(choices=[('standard', 'Vendeur Standard'), ('premium', 'Vendeur Premium')], default='standard', max_length=20),
        ),
        migrations.CreateModel(
            name='SellerSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=1000, max_digits=10)),
                ('method', models.CharField(choices=[('mtn', 'MTN Mobile Money'), ('orange', 'Orange Money')], max_length=10)),
                ('phone_number', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('active', 'Active'), ('expired', 'Expirée'), ('rejected', 'Refusée')], default='pending', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
