# Generated by Django 6.1.1 on 2026-09-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_admin_validated_order_admin_validated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='neighborhood',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='coursepayment',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('seller_delivered', 'Livrée par le vendeur'), ('customer_received', 'Réception confirmée'), ('delivered', "Validée par l'administrateur")], default='pending', max_length=20),
        ),
    ]
